Allow non-giant robots to gib under normal gibbing conditions
mastercomfig/team-comtress-2 pull request #126
Opened 2020-09-15 08:45 UTC by Thestickman391

Stolen from https://github.com/sigsegv-mvm/libtf2mod/blob/master/detour/robot_gib_improvements.c

2020-09-15 09:03 UTC, Yttrium-tYcLief commented
Originally posted in #127 but meant to go here:

This is going to need to be substantially performance tested, likely with a custom map, along with bugtested.

It's very likely that it wasn't originally done for performance reasons, but with the improvements to threading, performance might be OK in the current build. Will need testing.

2020-09-19 20:47 UTC, DrCactusTF2 commented
> 
> 
> Originally posted in #127 but meant to go here:
> 
> This is going to need to be substantially performance tested, likely with a custom map, along with bugtested.
> 
> It's very likely that it wasn't originally done for performance reasons, but with the improvements to threading, performance might be OK in the current build. Will need testing.

This has actually been tested and is still enabled on the potato.tf testing server, and it has had little performance impact compared to the already established rag doll rules

2020-09-21 18:14 UTC, maximsmol requested changes
This code
1) Will not even build because of undefined references
2) Was clearly copy-pasted from some reverse-engineered patch

Needs rework

2020-09-21 18:14 UTC, maximsmol commented on game/server/tf/bot/tf_bot.cpp
> +	if (CTFGameRules_IsPVEModeActive(*g_pGameRules) && CBaseEntity_GetTeamNumber(this) == TFTEAM_BLUE) {
Why not `TFGameRules()->IsMannVsMachineMode()`?
Why `CBaseEntity_GetTeamNumber` instead of `GetTeamNumber()`?

2020-09-21 18:14 UTC, maximsmol commented on game/server/tf/bot/tf_bot.cpp
> +		bool is_miniboss = CTFPlayer_IsMiniBoss(this);
Why not `IsMiniBoss()`?

2020-09-21 18:14 UTC, maximsmol commented on game/server/tf/bot/tf_bot.cpp
> +		float *m_flModelScale = (float *)((uintptr_t)this + off_CTFPlayer_m_flModelScale);
Why not `m_flModelScale`?

2020-09-21 18:14 UTC, maximsmol commented on game/server/tf/bot/tf_bot.cpp
> +		bool is_engie  = CTFPlayer_IsPlayerClass(this, TFCLASS_ENGINEER);
Why not `IsPlayerClass(...)`?

2020-09-21 18:15 UTC, maximsmol commented
Please at least build your changes before submitting!

2020-09-21 23:35 UTC, Thestickman391 commented
Made requested changes

2020-09-27 16:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mastercomfig/team-comtress-2?pullRequest=126) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mastercomfig/team-comtress-2?pullRequest=126) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mastercomfig/team-comtress-2?pullRequest=126) it.</sub>

2020-09-28 16:25 UTC, mastercoms requested changes
Please include the license for this code.

2020-09-30 05:39 UTC, Thestickman391 commented
Done

2020-09-30 07:36 UTC, Yttrium-tYcLief commented
If this content was simply lifted from sigsegv, we should probably reach out to him regarding the CLA.

2020-09-30 11:39 UTC, Thestickman391 commented
It's not copied verbatim  (most of it has been changed at this point actually) but yeah, thats probably a good idea.

2020-10-03 10:30 UTC, Thestickman391 commented
@sigsegv-mvm

2020-10-03 11:32 UTC, sigsegv-mvm commented
> If this code was simply lifted from sigsegv, we should probably reach out to him regarding the CLA. Considering his past history with TF2 patches and Valve, it likely wouldn't be a problem getting him to sign it.

I do appreciate you guys reaching out to me, and just generally taking appropriate steps like putting proper attribution of where the code came from and reproducing the BSD license statement and so forth.

——

As for any direct involvement between me and this project: unfortunately, I effectively find myself in a sort of “don’t touch the poop” scenario. Allow me to explain...

This project, to my understanding, is based on the recent illegally leaked source code which originated from some Source Engine licensee who egregiously violated their NDA contract with Valve.

I have not heard anything from Valve about what their particular stance is WRT this most recent code leak. I am, of course, aware that in some past instances, e.g. with the March 2008 Source Engine code leak (which included, among other things, early post-release Team Fortress 2 game code), Valve has made actual statements to the effect that they are basically fine with people using that particular code to make their own sourcemods; but only as long as it’s not for profit etc. And so, in my book, that particular corpus of Valve code is effectively fine to re-host and to build stuff on top of and so forth.

But, to my knowledge, Valve has never made any blanket statement about all code leaks being totally fine to do whatever you want with; and I haven’t heard any particular statement about this leak; and I don’t think it’s responsible to just automatically assume that Valve will necessarily do the same as they have done previously; and so, until/unless I *do* hear Valve make a statement regarding this particular leak being fine to mess around with like the 2008 leak, I have been (and continue to be) refusing to look at any of the code, reading any of the files, or doing literally anything with it. Because as far as I’m concerned, the status of leaked code is generally **”nope”**, unless/until Valve specifically does come out and says “yeah okay whatever, even though we would absolutely be within our rights to sue you, we promise we won’t, and you can do more-or-less what you like with the leaked code, within reasonable limits”.

From a very brief look, it appears that this project is redistributing effectively all of the recently leaked code; or at least, in any case, enough of it to build TF2. So in other words, this repository is actively hosting the leaked codebase (and *compiled binaries* built therefrom... that’s a bit of a “yikes”), whose legal status is still “don’t touch that” by default. If this repo just hosted a set of diffs / patch files that one could apply to the leaked source on their own, then my level of concern would be a fair bit lower.

——

So, that’s pretty much my take on what troubles me about ending up being directly involved in this project in any way; for the present time, at least, in any case.

If you guys want to port over some of my (mostly MvM-related) mods and things that I’ve done, like with this particular example, that’s fine with me and it’s entirely within your rights to do so. I chose the very loose Simplified BSD License for a reason.

As long as you consistently do proper attribution for whatever code you do use/adapt, and bring along the appropriate license blurb for it, it’s all fine and dandy to me.

But, I won’t be contributing to this repository myself, directly, on a personal level (let alone look at any leaked or leak-based code) until/unless my concerns about the legal situation are cleared up.

I hope that all makes sense. I certainly do appreciate the noble goals of this project. I just have misgivings about being personally involved at all until I’m sufficiently convinced that everything is well and truly on the up-and-up legally.

——

(And, actually, given all the above, I confess I’m not entirely sure what the direct impact on the actual answer to “do I sign a CLA or not?” is. My assumption is that probably it should lead to “no you shouldn’t sign it, then”; but I’m not entirely sure.)

(I guess basically my dilemma here is that I would like to have proper author attribution / be properly credited if my code is used in this project; but also I don’t know that I necessarily want to be categorized as a “contributor”, at least at the present time, because of my misgivings described above. If that makes sense.)

2020-10-03 11:45 UTC, mastercoms commented
Hi sigsegv! Thanks for reaching out. It's definitely understandable, and of course we will continue to use best practices when it comes to licenses and attribution.

As for this repo: yes, it is a bit of a difficult scenario. However, it is in this current state for ease of use, as patches would complicate the workflow for many, and get us less QA, review, and contributions. Unfortunately, these sorts of tricky scenarios are always going to be present when trying to work on a game we love so much without actually having a relationship with Valve.

I believe there is a legal issue with solely taking these patches into this repo under the BSD license. We don't have the rights to then present these changes to Valve as a project, and Valve probably wouldn't be comfortable with part of their game code being technically under this license. This is what the CLA ensures.

However, I do believe that you are very much capable of presenting these changes to Valve on your own, on your own terms, and probably have already done so. So I don't think it's beneficial/needed to include in this project, unless you _do_ want to explicitly have these changes in this project, and do end up signing the CLA.

You don't have to necessarily be listed as a contributor for that to happen, but it does certainly have _some_ level involvement you may not be comfortable with. And that's completely fine and understandable. No worries there.

2020-10-03 22:36 UTC, sigsegv-mvm commented
> I believe there is a legal issue with solely taking these patches into this repo under the BSD license. We don't have the rights to then present these changes to Valve as a project, and Valve probably wouldn't be comfortable with part of their game code being technically under this license. This is what the CLA ensures.

Okay. I think I understand what's going on there. And in the event that Valve wants to merge in the code under a different set of licensing terms, I would most certainly be fine with them doing that, by all means. I'm just a bit fuzzy on what specifically happens in the interim, though. (License-wise.)

Is there any straightforward way for me to effectively say "I hereby grant you permission to relicense any of my code that's been copied/adapted into this project *just for Valve, if and when they may request that it be relicensed as a condition for being accepted*", or something to that effect, short of fully signing onto the CLA myself?

Also, just as a point of clarification: what license is actually being used for submissions to this project right now, generally speaking? Judging by the ~~`LICENSE`~~`LICENSE_SDK` file in the project root being the Source SDK license, I would presume that that's the license that contributions are subject to? (Perhaps just for the time being, I guess?)

> However, I do believe that you are very much capable of presenting these changes to Valve on your own, on your own terms, and probably have already done so. So I don't think it's beneficial/needed to include in this project, unless you _do_ want to explicitly have these changes in this project, and do end up signing the CLA.
> 
> You don't have to necessarily be listed as a contributor for that to happen, but it does certainly have _some_ level involvement you may not be comfortable with. And that's completely fine and understandable. No worries there.

Well, I mean, like I've said, I'm perfectly fine with other people pulling in fixes and things that I've done; as long as I'm not personally directly involved, so that I can avoid "tainting" myself by looking at the leaked source code, essentially. 🙈

From reading the CLA, doesn't section 4 ("Third Party Content/Rights") effectively say that if someone contributes changes to this project which are based on third-party code (as in the case in this PR, where the contribution was done by someone else, and the third-party code is mine), and that person is signed onto the CLA, then everything is more-or-less fine? Or do I have some level of misunderstanding there? (For example, is the problem that, even under the provisions of section 4, the third-party contribution would remain under its original license terms, i.e. BSD in this case?)

----

Let me know about some of those clarifications, and then hopefully we can figure out something that works.

If there's no other way to make things work than un-BSD-ifying the code, I would be willing to consider that, as long as I have a relatively concrete understanding of what my code *is* potentially being relicensed into.

(I'm very much not a Richard Stallman type of guy; by which I mean to say, I'm not a fan of licenses intentionally being used as weapons or as a way of being obstructive; and that's *sometimes* what people intend when they use e.g. the GPL (though still it very much depends on whether you're a (semi-)crazy uber-idealist like Stallman who thinks that ACCESS TO UNPOLLUTED FREE SOFTWARE (WITH A CAPITAL 'F' AND A CAPITAL 'S') IS THE MOST IMPORTANT FUNDAMENTAL HUMAN RIGHT, MORE IMPORTANT THAN ACCESS TO CLEAN DRINKING WATER<sup id="a1">[1](#f1)</sup>; or just a pragmatist like Linus Torvalds, who used GPL for his kernel not for any particular ideological reason but because it happened to fit his particular project's needs). And that's part of why I've tended to license my stuff as BSD, which is pretty close to "do whatever you want, with a couple small caveats": I want the things I've worked on to be able to be useful to other people, and to not have the license get in the way. So that's my point of view; the intent of my licensing choices has been to make external use of the code easier, not harder, and as such, I'm willing to be flexible if need be.)

----

<b id="f1">1.</b> Sadly, this is only a *very minor* exaggeration of what RSM *actually believes*.[↩](#a1)

2020-10-03 23:01 UTC, mastercoms commented
> Is there any straightforward way for me to effectively say "I hereby grant you permission to relicense any of my code that's been copied/adapted into this project just for Valve, if and when they may request that it be relicensed as a condition for being accepted", or something to that effect, short of fully signing onto the CLA myself?

The reason I used this more general CLA is because I am not a lawyer, and ended up reusing another CLA. I am not sure how to write the CLA in a way that would be legally acceptable for the purpose you described, which I fully agree with personally.

> Also, just as a point of clarification: what license is actually being used for submissions to this project right now, generally speaking? Judging by the ~~`LICENSE`~~ `LICENSE_SDK` file in the project root being the Source SDK license, I would presume that that's the license that contributions are subject to? (Perhaps just for the time being, I guess?)

This repo in its entirety is unlicensed, which means that all rights for the work are reserved to their respective owners. The `LICENSE_SDK` is to clarify Valve's rights and conditions to the portions of this code which were licensed as part of the official SDK. They do not pertain to the repo as a whole.

> From reading the CLA, doesn't section 4 ("Third Party Content/Rights") effectively say that if someone contributes changes to this project which are based on third-party code (as in the case in this PR, where the contribution was done by someone else, and the third-party code is mine), and that person is signed onto the CLA, then everything is more-or-less fine? Or do I have some level of misunderstanding there? (For example, is the problem that, even under the provisions of section 4, the third-party contribution would remain under its original license terms, i.e. BSD in this case?)

Yep, basically the CLA is asking you to be sure that you _can_ submit the content to the repo, and to do so with the appropriate Third Party Rights. However, those Third Party Rights (BSD in this case), may be problematic in this case where it will be sent to Valve as modifications to their core engine/game code outside the realms of the `thirdparty` folder. We need the proper rights to be able to essentially "transfer" the code to them, without them having any concerns about possible loss of rights of part of their own code.

> If there's no other way to make things work than un-BSD-ifying the code, I would be willing to consider that, as long as I have a relatively concrete understanding of what my code is potentially being relicensed into.

Unfortunately, I don't have an answer about this beyond the broad assurances that the CLA gives us at the moment. I am not sure about the right way to go forward in terms of licensing this code, in a way that would make Valve comfortable in accepting patches to their own codebase. I am super understanding of your concern regarding how wide this CLA is, and that it isn't strictly expressing our goal of submitting this to Valve. If you have any recommendations on how to move forward regarding this, I would be open to suggestions, as long as they have a strong legal foundation, like the CLA this project's CLA is based on.

2020-11-19 16:28 UTC, closed without merging