VRAD: Fix thread-sharing bug
mastercomfig/team-comtress-2 pull request #141
Opened 2020-09-15 15:41 UTC by devvoid

The raytracing code has debug variable `n_intersection_calculations`. This was used solely for debugging, but its existence caused a massive bottleneck in VRAD; performance nearly doubles on some systems without it.

More information and some performance testing can be found here: https://github.com/ValveSoftware/source-sdk-2013/pull/436

2020-09-15 21:35 UTC, mastercoms requested changes
Could you wrap these in `#ifdef _DEBUG` / `#endif`?

2020-09-15 21:43 UTC, devvoid commented
Just in raytrace, or in float_bm4 too?

2020-09-15 21:44 UTC, devvoid commented
Also, the original code doesn't work as-intended because it isn't an atomic int and the raytracing system is multithreaded. I can also go ahead and change that too.

2020-09-15 23:06 UTC, GamerDude27 requested changes

2020-09-15 23:06 UTC, GamerDude27 commented on raytrace/raytrace.cpp
> +					num_intersection_calculations++;
Typo, should be `n_intersection_calculations`!

2020-09-16 23:54 UTC, GamerDude27 commented
Out of curiosity, is the `std::atomic<int>` part something TC2 specific or does this count for, say, SDK2013 as well?

2020-09-17 00:46 UTC, GamerDude27 commented
Additionally, the linked PR also proposes upping `MAX_THREADS` and `MAX_TOOLS_THREADS` from 16 to 32, would this be relevant for TC2?

2020-09-17 02:41 UTC, mastercoms approved these changes

2020-09-17 02:41 UTC, mastercoms commented
@GamerDude27 Please move the MAX_THREADS discussion to a new issue, thanks!

2020-09-17 02:41 UTC, merged

2020-09-17 03:59 UTC, GamerDude27 commented
@mastercoms I'm still curious about my first question though!

2020-10-07 18:05 UTC, micwoj92 commented
rip bro @devvoid