Prevent sv_alltalk 1 exposing cloaked spies who are talking
mastercomfig/team-comtress-2 pull request #155
Opened 2020-09-16 00:50 UTC by Thestickman391

2020-09-16 05:43 UTC, micwoj92 commented
This should be made into cvar and old behaviour set as default.

2020-09-16 05:46 UTC, Yttrium-tYcLief commented
Why would we *want* this to persist in the game?

2020-09-16 05:48 UTC, mastercoms approved these changes

2020-09-16 05:48 UTC, mastercoms requested changes
Could you check for sv_alltalk?

2020-09-16 05:49 UTC, micwoj92 commented
> Why would we _want_ this to persist in the game?

Trolling.

2020-09-16 06:32 UTC, wgetJane requested changes
this looks it would cause the speech bubble to always appear for teammates even if they're not speaking

2020-09-16 06:32 UTC, wgetJane commented on game/client/tf/vgui/tf_overview.cpp
> +	if ( cl_voicetest.GetInt() || GetClientVoiceMgr()->IsPlayerSpeaking( player->index+1 ) && !pPlayer->m_Shared.IsFullyInvisible() || InSameTeam( pPlayer ) )
```suggestion
	if ( cl_voicetest.GetInt() || ( GetClientVoiceMgr()->IsPlayerSpeaking( player->index+1 ) && ( !pPlayer->m_Shared.IsFullyInvisible() || InSameTeam( pPlayer ) ) ) )
```

fix this logical expression

2020-09-17 02:57 UTC, maximsmol commented
Besides adding a check for `sv_alltalk` we should also actually test it to make sure @wgetJane's version of the check works properly (I am rather certain the old one was broken)

2020-09-17 03:12 UTC, Thestickman391 commented
Added a check for sv_alltalk

2020-09-19 18:32 UTC, maximsmol commented
Ok, perfect. Assuming that this was tested and merging since Jane saw it too.

2020-09-19 18:32 UTC, merged