Use SetPlayerName instead of cl_name in CTFBotSpawner::Spawn
mastercomfig/team-comtress-2 pull request #198
Opened 2020-09-17 01:23 UTC by Thestickman391

2020-09-17 02:50 UTC, maximsmol commented
Does this come with any kind of improvement? Or is this just because it makes more sense?

2020-09-17 03:09 UTC, melvyn2 commented
It would allow bots to work properly even if the `cl_name` command is blacklisted, which IMO it should be.

2020-09-21 18:23 UTC, maximsmol requested changes

2020-09-21 18:23 UTC, maximsmol commented on game/server/tf/player_vs_environment/tf_populator_spawners.cpp
> +		newBot->SetPlayerName(m_name.Get());
Add the `IsEmpty` check from the old version.

2020-09-21 23:42 UTC, Thestickman391 commented
Made requested changes

2020-09-26 21:54 UTC, mastercoms commented
What sort of new pathways are we going through when we use SetPlayerName?

2020-09-27 16:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mastercomfig/team-comtress-2?pullRequest=198) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mastercomfig/team-comtress-2?pullRequest=198) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mastercomfig/team-comtress-2?pullRequest=198) it.</sub>

2020-11-19 16:30 UTC, closed without merging