Re-enable special robot headshot animations
mastercomfig/team-comtress-2 pull request #235
Opened 2020-09-19 05:28 UTC by Thestickman391

2020-09-19 05:32 UTC, wgetJane commented
are these animations specifically made for the robots or do they just use human animations?

2020-09-19 05:33 UTC, Thestickman391 commented
They are made specifically for the robots, aside from the engineer

2020-09-21 18:18 UTC, maximsmol approved these changes
Changes LGTM. Why was this disabled in the first place though? Are these animations buggy?

2020-09-21 23:57 UTC, Thestickman391 commented
[Nope](https://www.youtube.com/watch?v=UhvdkCp5of8)

2020-09-22 22:47 UTC, Yttrium-tYcLief commented
They were implemented and simply disabled for some reason. I'm going to see about stress-testing these, in case there's an actual valid reason for them to have been disabled.

2020-09-24 04:44 UTC, mastercoms requested changes

2020-09-24 04:44 UTC, mastercoms commented on game/shared/tf/tf_player_shared.cpp
> -	if ( TFGameRules() && TFGameRules()->IsMannVsMachineMode() )
Surround this with #ifdef VALVE_PURE.

2020-09-24 05:34 UTC, Thestickman391 commented
Done

2020-09-26 21:50 UTC, mastercoms approved these changes

2020-09-26 21:50 UTC, merged