Fix for Tough Break Universal Switch speed buff breaking robots
mastercomfig/team-comtress-2 pull request #265
Opened 2020-09-19 23:14 UTC by Thestickman391

Closes #258

2020-09-20 22:12 UTC, Thestickman391 commented
Also closes #224

2020-09-21 17:22 UTC, maximsmol requested changes
Thanks for the patch! Take a second look at the `reinterpret_cast`s please

2020-09-21 17:22 UTC, maximsmol commented on game/server/tf/bot/tf_bot.cpp
> +				if (CTFBotUseBuffItem::IsPossible( reinterpret_cast<CTFBot *>( this ) ) ) {
Why is the `reinterpret_cast` needed? Is `this` not of type `CTFBot*` already? If not, could a `dynamic_cast` work instead?

2020-09-21 17:22 UTC, maximsmol commented on game/server/tf/bot/tf_bot.cpp
> +					if (CTFBotUseLunchBoxItem::IsPossible( reinterpret_cast<CTFBot *>( this ) ) ) {
ditto

2020-09-21 23:56 UTC, Thestickman391 commented
You are correct - changes made

2020-09-27 16:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mastercomfig/team-comtress-2?pullRequest=265) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mastercomfig/team-comtress-2?pullRequest=265) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mastercomfig/team-comtress-2?pullRequest=265) it.</sub>

2020-11-19 16:30 UTC, closed without merging