Add `unalias`
mastercomfig/team-comtress-2 pull request #73
Opened 2020-09-13 19:42 UTC by maximsmol

Adds the reverse of the `alias` command so if existing cvars are `alias`'d by accident they can be restored without restarting the game.

2020-09-15 09:17 UTC, Yttrium-tYcLief commented
>Also reformatted the alias implementation to be less 1990s.

What do you mean by this?

2020-09-15 09:19 UTC, micwoj92 commented
> > Also reformatted the alias implementation to be less 1990s.
> 
> What do you mean by this?

He is zoomer and hates old code.

2020-09-15 09:20 UTC, Yttrium-tYcLief commented
Oh, just code cleanup - for some reason I thought he meant he changed the syntax used, and got worried about compatibility.

I think I need to sleep.

2020-09-15 20:45 UTC, mastercoms requested changes
Could you revert your changes to the alias command and move them to another PR?

2020-09-27 16:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mastercomfig/team-comtress-2?pullRequest=73) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mastercomfig/team-comtress-2?pullRequest=73) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mastercomfig/team-comtress-2?pullRequest=73) it.</sub>

2020-09-30 22:03 UTC, maximsmol commented
Closing since I won't actually ever fix this

2020-09-30 22:03 UTC, closed without merging